---
name: Test-Without
version: 0.10
author:
  - 'Randy J. Ray <rjray@blackperl.com>'
abstract: Hide directories and/or modules from test blocks
license: perl
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Test-Without
  homepage: http://search.cpan.org/dist/Test-Without
  license: http://dev.perl.org/licenses/
  repository: http://github.com/rjray/test-without
build_requires:
  Test::More: 0.80
requires:
  Scalar::Util: 1.21
  perl: 5.008
configure_requires:
  Module::Build: 0.35
provides:
  Test::Without:
    file: lib/Test/Without.pm
    version: 0.100
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
